name: SAFE META package release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tool Restore
        run: dotnet tool restore

      - name: Release
        working-directory: ./Build
        env:
          VERSION: ${{ github.ref_name }}
          RELEASE_NOTES_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES_BODY: ${{ github.event.release.body }}
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: dotnet run --project Build.fsproj -- Publish
