name: SAFE meta automated tests

on: push

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install Node
                uses: actions/setup-node@v4
                with:
                    node-version: 18

            -   name: Tool Restore
                run: dotnet tool restore

            -   name: Test
                working-directory: ./Build
                run: dotnet run --project Build.fsproj -- Test